#encoding: utf-8
#Cities
City::find_or_create_by_name 'New York'
City::find_or_create_by_name 'Los Angeles'
City::find_or_create_by_name 'Chicago'
City::find_or_create_by_name 'Houston'
City::find_or_create_by_name 'Philadelphia'
City::find_or_create_by_name 'Phoenix'
City::find_or_create_by_name 'San Diego'
City::find_or_create_by_name 'San Antonio'
City::find_or_create_by_name 'Dallas'
City::find_or_create_by_name 'Detroit'
City::find_or_create_by_name 'San Jose'
City::find_or_create_by_name 'Indianapolis'
City::find_or_create_by_name 'Jacksonville'
City::find_or_create_by_name 'San Francisco'
City::find_or_create_by_name 'Columbus'
City::find_or_create_by_name 'Austin'
City::find_or_create_by_name 'Memphis'
City::find_or_create_by_name 'Baltimore'
City::find_or_create_by_name 'Charlotte'
City::find_or_create_by_name 'Fort Worth'
City::find_or_create_by_name 'Boston'
City::find_or_create_by_name 'Milwaukee'
City::find_or_create_by_name 'El Paso'
City::find_or_create_by_name 'Washington'
City::find_or_create_by_name 'Nashville-Davidson'
City::find_or_create_by_name 'Seattle'
City::find_or_create_by_name 'Denver'
City::find_or_create_by_name 'Las Vegas'
City::find_or_create_by_name 'Portland'
City::find_or_create_by_name 'Oklahoma City'
City::find_or_create_by_name 'Tucson'
City::find_or_create_by_name 'Albuquerque'
City::find_or_create_by_name 'Atlanta'
City::find_or_create_by_name 'Long Beach'
City::find_or_create_by_name 'Kansas City'
City::find_or_create_by_name 'Fresno'
City::find_or_create_by_name 'New Orleans'
City::find_or_create_by_name 'Cleveland'
City::find_or_create_by_name 'Sacramento'
City::find_or_create_by_name 'Mesa'
City::find_or_create_by_name 'Virginia Beach'
City::find_or_create_by_name 'Omaha'
City::find_or_create_by_name 'Colorado Springs'
City::find_or_create_by_name 'Oakland'
City::find_or_create_by_name 'Miami'
City::find_or_create_by_name 'Tulsa'
City::find_or_create_by_name 'Minneapolis'
City::find_or_create_by_name 'Honolulu'
City::find_or_create_by_name 'Arlington'
City::find_or_create_by_name 'Wichita'
City::find_or_create_by_name 'St. Louis'