#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
::Rails.logger.level = Logger::ERROR
Delayed::Command.new(ARGV).daemonize
